[parity]
chain = "init.json"

[network]
#bootnodes = []

[rpc]
disable = true

[websockets]
disable = true

[account]
#password = ["/home/parity/.local/share/io.parity.ethereum/password.pwd"]

[mining]
#engine_signer = ""
reseal_on_txs = "none"
force_sealing = true
